#! /bin/bash
#
if [ -z "$1" ]; then
    echo Sync target time/RTC with system time
    echo -e
    echo Usage:
    echo "  $0 <serial port number>"
    echo "    The serial port should fully reflect ACM or USB followed by a digit"
    p_found=0
    for fl in "/dev/ttyACM" "/dev/ttyUSB"; do
        if ls $fl* 1> /dev/null 2>&1; then
            echo Available ports:
            for fn in $fl*; do
                echo -n "  ${fn#*tty}"
            done
            p_found=1
        fi
    done
    if [ $p_found -eq 1 ]; then
        echo -e
    else
        echo No suitable ports found.
    fi
    exit 1
fi
date +'%g%m%d DATE! %H%M%S QTIME!' > /dev/tty$1 && echo -e "\r" > /dev/tty$1
