#! /bin/bash
#
if [ -z "$1" ]; then
    echo Start a minicom session with the specified system
    echo -e
    echo Usage:
    echo "  $0 <USB port number>"
    if ls /dev/ttyUSB* 1> /dev/null 2>&1; then
        echo Available ports:
        for fn in /dev/ttyUSB*; do
            echo -n "  ${fn#*ttyUSB}"
        done
        echo -e
    else
        echo No suitable ports found.
    fi
    exit 1
fi
minicom --color=on --ansi -w -b 921600 -D /dev/ttyUSB$1

